package com.sim.elasticsearch.post

import com.sim.domain.inspectedpost.InspectedPost

object PostDocumentConverter {

    fun toDocument(post: InspectedPost): PostDocument {
        return PostDocument(
            id = post.post.id,
            title = post.post.title,
            content = post.post.content,
            categoryName = post.categoryName,
            tags = post.autoGeneratedTags
        )
    }
}