package com.sim.domain.inspectedpost

import com.sim.domain.post.Post
import java.time.LocalDateTime

data class InspectedPost(
    val post: Post,
    val categoryName: String,
    val autoGeneratedTags: List<String>,
    val inspectedAt: LocalDateTime = LocalDateTime.now()
) {
}