package com.sim.kafka.adapter.inspectedpost

import com.sim.domain.inspectedpost.InspectedPost
import com.sim.domain.post.Post
import com.sim.kafka.common.OperationType
import java.time.LocalDateTime

data class InspectedPostMessage(
    val id: String,
    val operationType: OperationType,
    val payload: Payload?
) {

    data class Payload(
        val post: Post,
        val categoryName: String,
        val autoGeneratedTags: List<String>,
        val inspectedAt: LocalDateTime
    ) {
        companion object {
            fun from(inspectedPost: InspectedPost): Payload {
                return Payload(
                    post = inspectedPost.post,
                    categoryName = inspectedPost.categoryName,
                    autoGeneratedTags = inspectedPost.autoGeneratedTags,
                    inspectedAt = inspectedPost.inspectedAt
                )
            }
        }
    }

    companion object {
        fun from(inspectedPost: InspectedPost, operationType: OperationType): InspectedPostMessage {
            return InspectedPostMessage(
                id = inspectedPost.post.id,
                operationType = operationType,
                payload = Payload.from(inspectedPost)
            )
        }

        fun from(id: String, operationType: OperationType): InspectedPostMessage {
            return InspectedPostMessage(
                id = id,
                operationType = operationType,
                payload = null
            )
        }
    }
}
